### ISSUE TITLE
GPL license doesn't seem to be properly specified

### ISSUE THREAD

**Issue by jrmarino** [mtsuszycki/whowatch#5]
I understand there is a copy of the GPL in the repository (COPYING).  However, its presence by itself doesn't mean anything.  There should be at least one file specifying its use, either a separate file or in a source file or header.

Per COPYING:
```
            How to Apply These Terms to Your New Programs

  If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.

  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
convey the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
```

That block is just a template.  If whowatch is GPL-licensed (and I'm only guessing that it is), then that template should be filled out and added somewhere (I suggest either separate LICENSE file or at the beginning of src/whowatch.h at least).  

FYI, the licensing scheme at ravenports has updated.
Due to the missing terms above, I'm going to remove the GPLv2 listing since I GPLv* licenses require the terms to extract and I can't extract them from this release.

see: http://www.ravenports.com/catalog/bucket_0F/whowatch/standard/

**Comment by pabs3** [comment]
There is indeed no license grant anywhere in the codebase.

I don't know how I missed this in all the years I worked on it.

I'll contact the original author about this issue.

I'd suggest that we add the license grants to each file:

http://lu.is/blog/2012/03/17/on-the-importance-of-per-file-license-information/

I'd also suggest that we add SPDX-License-Identifier fields:

https://spdx.org/using-spdx-license-identifier
